spring:
  application:
    name: 'faturamento'
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:icompras-faturamento}
      auto-offset-reset: earliest

server:
  port: 8084

icompras:
  config:
    kafka:
      topics:
        pedidos-pagos: ${KAFKA_TOPIC_PEDIDOS_PAGOS:icompras.pedidos-pagos}
        pedidos-faturados: ${KAFKA_TOPIC_PEDIDOS_FATURADOS:icompras.pedidos-faturados}

springdoc:
  open-api:
    title: MS de Faturamentos
    description: Microserviço de gerenciamento de faturamentos
    version: 1.0.0

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:icompras.faturas}