spring:
  application:
    name: 'faturamento'

server:
  port: 8084

minio:
  endpoint: 'http://localhost:9000'
  access-key: 'minioadmin'
  secret-key: 'minioadmin'
  bucket-name: 'icompras.faturas'